version: "3"
services:
  directus:
    env_file:
      - .env
    image: directus/directus:10.10.4
    restart: always
    ports:
      - 8055:8055
    volumes:
      - ./extensions:/directus/extensions
    environment:
      KEY: "${KEY}"
      SECRET: "${SECRET}"

      DB_CLIENT: "pg"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"

      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "${REDIS}"

      STORAGE_LOCATIONS: "supabase"
      STORAGE_SUPABASE_DRIVER: "supabase"
      STORAGE_SUPABASE_SERVICE_ROLE: "${STORAGE_SUPABASE_SERVICE_ROLE}"
      STORAGE_SUPABASE_BUCKET: "${STORAGE_SUPABASE_BUCKET}"
      STORAGE_SUPABASE_PROJECT_ID: "${STORAGE_SUPABASE_PROJECT_ID}"

      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
